# Generated by Django 4.2.7 on 2026-02-14 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('crm', models.CharField(max_length=20)),
                ('uf_crm', models.CharField(max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MedicoEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_minutos', models.PositiveIntegerField(default=30)),
                ('valor_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
            options={
                'verbose_name': 'Vínculo Médico-Especialidade',
                'verbose_name_plural': 'Vínculos Médico-Especialidade',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(related_name='medicos', through='clinica.MedicoEspecialidade', to='clinica.especialidade'),
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('rua', models.CharField(blank=True, max_length=40, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Quem criou?')),
                ('usuario_exclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_excluidos', to=settings.AUTH_USER_MODEL, verbose_name='Quem excluiu?')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
                ('hora_agendamento', models.TimeField(verbose_name='Hora do Agendamento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('AG', 'Agendado'), ('CA', 'Cancelado'), ('FA', 'Faltou')], default='AG', max_length=2, verbose_name='Status do Agendamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.contato')),
            ],
            options={
                'ordering': ['-data_agendamento', '-hora_agendamento'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicoespecialidade',
            constraint=models.UniqueConstraint(fields=('medico', 'especialidade'), name='uniq_medico_especialidade'),
        ),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('crm', 'uf_crm'), name='uniq_crm_uf'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['medico', 'data_agendamento', 'hora_agendamento'], name='clinica_age_medico__271be5_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['paciente', 'data_agendamento', 'hora_agendamento'], name='clinica_age_pacient_9faf19_idx'),
        ),
    ]
