# Generated by Django 4.2.7 on 2023-12-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
