# Generated by Django 4.2.7 on 2023-12-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0002_contato_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_exclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='usuario_exclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_excluidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
