# Generated by Django 4.2.7 on 2023-12-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_contato_data_exclusao_contato_usuario_exclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
