# Generated by Django 4.2.7 on 2025-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AG', 'Agendado'), ('CA', 'Cancelado'), ('FA', 'Faltou')], default='AG', max_length=2, verbose_name='Status do Agendamento'),
        ),
    ]
