from django.urls import path
from clinica.views import (
   cadastro,
   medico_list,
   sucesso, 
   deletar_contato, 
   ClinicaListView, 
   ClinicaUpdateView, 
   cadastrar_usuario, 
   index, 
   login, 
   deslogar_usuario, 
   logar_usuario, 
   agendar_consulta, 
   listar_agendamentos, 
   agendamentos_json, 
   detalhes_paciente, 
   editar_agendamento,
   medico_create,
   medico_update,
   deletar_medico,
   especialidade_create_ajax,
   especialidades_por_medico,
   financeiro_list,
   financeiro_medico_detalhe
)


# URL patterns for the clinica app
urlpatterns = [
   path('logar_usuario/', logar_usuario, name="root"),
   path('logar_usuario/', logar_usuario, name="logar_usuario"),
   path('cadastrar_usuario/', cadastrar_usuario, name="cadastrar_usuario"),
   path('deslogar_usuario/', deslogar_usuario, name="deslogar_usuario"),
   path('index/', index, name="index"),
   path('clinica_list/', ClinicaListView.as_view(), name='clinica_list'),
   path('clinica_update/<int:pk>/', ClinicaUpdateView.as_view(), name='clinica_update'),
   path('deletar_contato/<int:pk>/', deletar_contato, name='deletar_contato'),
   path('contato_form/', cadastro, name='contato_form'),
   path('sucesso/', sucesso, name='sucesso'),
   path('agendar_consulta/', agendar_consulta, name='agendar_consulta'),
   path('listar_agendamentos/', listar_agendamentos, name='listar_agendamentos'),
   path('agendamentos-json/',  agendamentos_json, name='agendamentos_json'),
   path('paciente/<int:pk>/', detalhes_paciente, name='detalhes_paciente'),
   path('agendamento/<int:agendamento_id>/editar/', editar_agendamento, name='editar_agendamento'),   
   path("medicos/", medico_list, name="medico_list"),
   path("medicos/novo/", medico_create, name='medico_create'),
   path("medicos/<int:pk>/editar/", medico_update, name='medico_update'),
   path("medicos/<int:pk>/excluir/", deletar_medico, name='medico_delete'),
   path("especialidades/ajax/criar", especialidade_create_ajax ,name='especialidade_create_ajax'),
   path("api/especialidades-por-medico/", especialidades_por_medico, name='especialidades_por_medico'),
   path("deletar_medico/<int:pk>/excluir/", deletar_medico, name='deletar_medico'),
   path('financeiro/', financeiro_list, name='financeiro_list'),
   path('financeiro/medico/<int:pk>/', financeiro_medico_detalhe, name='financeiro_medico_detalhe'),
]
